---

- name: Update packages cache
  ansible.builtin.apt:
    update_cache: true

- name: Install prerequisites
  package:
    name: "{{ item }}"
    state: present
  loop:
    - python3
    - python3-pip

- name: Install Ansible
  pip:
    name: ansible
    state: latest