apiVersion: v1
kind: Secret
metadata:
  name: wordpress-secrets
type: Opaque
data:
  WORDPRESS_DB_HOST: bXlzcWwtc2VydmljZQ==
  WORDPRESS_DB_NAME: ZGJOYW1l
  WORDPRESS_DB_USER: dXNlcg==
  WORDPRESS_DB_PASSWORD: cGFzc3dvcmQ=
---
apiVersion: v1
kind: Secret
metadata:
  name: mysql-secrets
type: Opaque
data:
  MYSQL_ROOT_PASSWORD: cGFzc3dvcmQ=
  MYSQL_DATABASE: ZGJOYW1l
  MYSQL_USER: dXNlcg==
  MYSQL_PASSWORD: cGFzc3dvcmQ=