---

- name: Install Logstash
  ansible.builtin.apt:
    name: logstash
    state: present

- name: Configure Logstash
  ansible.builtin.template:
    src: etc/logstash/conf.d/beats.conf.j2
    dest: /etc/logstash/conf.d/beats.conf
  # notify:
  #   - restart logstash

- name: restart logstash
  ansible.builtin.systemd:
    name: logstash
    state: restarted
    enabled: true